# -*- mode: python -*-

Import('env')
env = env.Clone()

env.Append(LIBS=['cppunit'])

source = [
    env['RA_DO_TEST'],
    'MetricFetcherTest.cpp',
]

libs = [
    'contrib_filesystem',
    'ra_fetcher',
    'ra_common',
    'ra_util',
    'ra_test_util',
    'cppunit',
    'log4cplus',
    'glog',
]

ra_fetcher_test = env.UnitTest(target = 'ra_fetcher_test',
                               source = source,
                               LIBS = libs)

