# -*- mode: python -*-

Import('env')
env = env.Clone()

source = [
    'LocalFileSystem.cpp',
]

libs = [
    'dl',
]

env.compileAndInstallLibrary(target = 'local_filesystem',
                            sources = source,
                            package = 'red_alert',
                            libs = libs)
