# -*- mode: python -*-

Import('env')
env = env.Clone()

libconfig_sources = [
    'ConsistentHash.cpp',
    'Util.cpp',
    'FileUtil.cpp',
    'ConfigUtil.cpp',
    'SqlData.cpp',
    'MD5.cpp',
    'StringHash.cpp',
    'ThreadLock.cpp',
    'ThreadPool.cpp',
]

util_libs = [
    'log4cplus', 'curl', 'sqlite3', 'cppunit', 'dl',
]

  
env.compileAndInstallLibrary(
    target = 'ra_util',
    sources = libconfig_sources,
    package = "red_alert",
    libs = util_libs)

env.SConscript(dirs='test', exports='env')
