# -*- mode: python -*-

Import('env')
env = env.Clone()

env.Append(LIBS=['cppunit'])

source = [
    env['RA_DO_TEST'],
    'GraphiteMetricFetcherTest.cpp',
]

libs = [
    'ra_fetcher',
    'ra_common',
    'ra_util',
    'graphite_fetcher',
    'ra_test_util',
    'cppunit',
    'log4cplus',
]

env.UnitTest(target = 'graphite_fetcher_test',
             source = source,
             LIBS = libs)
