# -*- mode: python -*-

Import('env')
env = env.Clone()

source = [
    'DummyMetricFetcher.cpp',
]

libs = [
    'ra_common', 'ra_fetcher', 'dl',
]

env.compileAndInstallLibrary(target = 'dummy_fetcher',
                            sources = source,
                            package = 'red_alert',
                            libs = libs)

#env.SConscript(dirs='test', exports='env')

