# -*- mode: python -*-

# Inherit the environment from my parent.
Import('env')

# Make a copy of the environment, so my changes are limited in this directory and sub-directories.
env = env.Clone()


env.Append(LIBS=['cppunit'])

ra_tree_test_sources=  [
    env['RA_DO_TEST'],
    'MetricTreeTest.cpp',
    'RequestPackageTest.cpp',
    'ProcessPackageTest.cpp',
    'TreeManagerTest.cpp',
    ]

libsname = ['contrib_filesystem', 'ra_app', 'ra_tree', 'ra_service', 'ra_process', 'ra_test_util', 'ra_config', 'ra_util', 'ra_fetcher', 'glog', 'cppunit']
ra_tree_test = env.UnitTest(target = 'ra_tree_test',
                            source = ra_tree_test_sources,
                            LIBS = libsname)

